version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/deploy

file_exists_behavior: OVERWRITE
 
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 10
      runas: ubuntu
